name: tri-channel-oect-mc
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - pip
  - pip:
      - -e .[dev]
      - numpy>=2.3.3
      - scipy>=1.16.2
      - pandas>=2.3.2
      - matplotlib>=3.10.6
      - PyYAML>=6.0.3
      - tqdm>=4.67.1
      - rich>=14.1.0
      - psutil>=7.1.0
      - joblib>=1.5.2
      - statsmodels>=0.14.5
      - cycler>=0.12.1
      - seaborn>=0.13.2
      - pyarrow>=21.0.0
