name: tri-channel-oect-mc
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - pip
  - pip:
      - -e .[dev]
      - numpy>=2.3.2
      - scipy>=1.16.1
      - pandas>=2.3.1
      - matplotlib>=3.10.5
      - PyYAML>=6.0.2
      - tqdm>=4.67.1
      - rich>=14.1.0
      - psutil>=7.0.0
      - cycler>=0.12.1
      - seaborn>=0.13.2
