# Corrected default.yaml Configuration

# -------- Physical & biological constants --------
alpha: 0.20                      # ECS volume fraction
clearance_rate: 0.1             # s^-1 (k')
detection_bandwidth_Hz: 100  # Detection bandwidth (not sampling rate!)

# -------- Neurotransmitter-specific parameters ----
neurotransmitters:
  GLU:
    D_m2_s: 7.6e-10
    lambda: 1.6                  # CORRECTED: Consistent with literature (was 1.7)
    k_on_M_s: 1e5               # matches manuscript Table I
    k_off_s: 0.1
    q_eff_e: -1.0                # CORRECTED: Will be divided by lambda in code (was 1.6)
    damkohler: 0.024
  GABA: # dopamine
    D_m2_s: 6.0e-10             # CORRECTED: Same as GLU for consistency (was 9.1e-10)
    lambda: 1.6                 # CORRECTED: Consistent with GLU (was 1.5)
    k_on_M_s: 2.5e5
    k_off_s: 0.025                # CORRECTED: More realistic (was 0.9)
    q_eff_e: 1.0                # CORRECTED: Will be divided by lambda in code (was 0.5)
    damkohler: 0.010
  CTRL:
    k_on_M_s: 0                 # no binding
    k_off_s: 0                  # CORRECTED: Weaker binding (was 3.0)
    q_eff_e: 0                  # Smaller charge effect
    D_m2_s: 7.6e-10             # Same as GLU (for diffusion calculations)
    lambda: 1.6                 # CORRECTED: Same tortuosity as GLU (was 1.7)
    damkohler: 0.024            # Similar transport effects

# -------- Geometry --------
gate_area_m2: 4e-8              # 200x200 μm²

# -------- Release profile --------
T_release_ms: 10
burst_shape: "rect"             # "rect" | "gamma"
gamma_shape_k: 2.0              # used only if burst_shape == "gamma"
gamma_scale_theta: 5e-3         # s

# -------- Binding layer --------
#N_apt: 2e8                      # CORRECTED: Consistent with literature (was 4e8)
#binding:
  #k_on_M_s: 1e6                 # Changed from k_on_M_inv_s
  #k_off_s: 0.1                  # Changed from k_off_s_inv  
  #N_sites: 200000
  #N_sites_glu: 1e9              # CORRECTED
  #N_sites_gaba: 1e9             # CORRECTED
  #N_sites_ctrl: 0               # CTRL channel

# -------- OECT device --------
oect:
  gm_S: 0.005                     # FIXED: 10mS for better signal (was 0.005)
  C_tot_F: 4e-7                   # CORRECTED: 18 nF (was 2.4e-7 = 240 nF) - CRITICAL FIX (for 12nm film)
  R_ch_Ohm: 500                   # Channel resistance for Johnson noise
  I_dc_A: 1.0e-4                  # 1 µA baseline current for proper noise scaling
  V_g_bias_V: -0.2                # -200 mV gate bias

# -------- Noise --------
noise:
  rho_corr: 0.9
  alpha_H: 3.0e-3                 # larger Hooge ⇒ more 1/f noise (Reduced from 3.0e-3 (less 1/f noise))
  K_d_Hz: 1e-5                  # stronger 1/f² drift (Reduced from 1.0e-4 (less drift noise))
  N_c: 4.5e10                     # CORRECTED: Literature standard (was 6.0e12)

# -------- Simulation window --------
monte_carlo_trials: 10000
sim:
  #time_window_s: 20
  dt_s: 0.01
  temperature_K: 310.0

# ——— Simulation / figure sweeps ———
distances_um: [25, 50, 75, 100, 150, 175, 200, 225, 250]  # extended range
Nm_range: [2e2, 5e2, 1e3, 2e3, 5e3, 1e4, 2e4, 5e4, 1e5]  # finer resolution

# -------- Detection layer --------
detection:
  modulation: "MoSK"            # MoSK | CSK | hybrid
  #decision_window_s: 150        # CORRECTED: Optimal timing (was 8.0) - CRITICAL FIX
  threshold_nA:                 # only used for CSK (2-level) or CTRL threshold tests
    GLU: 0.75e-9
    GABA: 0.60e-9
  sequence_length: 1000         # symbols per Monte-Carlo run
  monte_carlo_trials: 10000
  snr_dB_range: [-10, 20]       # analytic BER curves

# -------- End-to-end pipeline --------
pipeline:
  #symbol_period_s: 150.0          # Ts from manuscript
  distance_um: 100              # transmitter-receiver spacing
  Nm_per_symbol: 5.0e4           # molecules per burst (high symbol) (Doubled from 1e4)
  sequence_length: 1000          # symbols per Monte-Carlo run
  random_seed: 2025
  modulation: "MoSK"            # Options: "MoSK", "CSK", "Hybrid"  # --- MASTER SWITCH ---
  enable_isi: True              # Master switch for the Inter-Symbol Interference model
  isi_memory: 2                 # Default memory (will be made dynamic in analysis script)
  guard_factor: 0.2             # 20% guard time (Reduced from 0.3)
  lod_nm_min: 50                # New flexible lower bound for LoD search
  csk_target_channel: "GLU"     # Defines the molecule used for the pure CSK scheme
  level_probs: [0.25, 0.25, 0.25, 0.25]  # For energy-fairness calculations
  csk_levels: 2                 # Number of concentration levels for CSK and Hybrid modes
  non_specific_binding_factor: 0.0  # FIXED: No signal leakage (was 0.05)
  channel_spacing_um: 200       # from paper
  # Channel positions relative to organoid center
  channel_positions:
    GLU: {x: -200, y: 0, z: 0}    # μm
    GABA: {x: 0, y: 0, z: 0}      # μm
    CTRL: {x: 200, y: 0, z: 0}    # μm
  # Gate dimensions for each channel
  gate_dimensions_um:
    width: 200
    height: 200
  # Aptamer specificity matrix (perfect selectivity assumed)
  #aptamer_specificity:
    #GLU: {GLU: 1.0, GABA: 0.0}    # GLU aptamers only bind GLU
    #GABA: {GLU: 0.0, GABA: 1.0}   # GABA aptamers only bind GABA
    #CTRL: {GLU: 0.05, GABA: 0.05}  # CORRECTED: 5% cross-reactivity (was 0.001)
  # Channel-specific aptamer counts (tri-channel architecture)
  N_sites_glu: 4e8              # FIXED: Double to prevent saturation (was 8e8)
  N_sites_gaba: 4e8             # FIXED: Double to prevent saturation (was 8e8)
  N_sites_ctrl: 0             # FIXED: No aptamers on control (was 4e8)
  enable_molecular_noise: true   # Enable Poisson shot noise
  channel_distances:
    GLU: 100.0                   # µm from organoid
    GABA: 100.0                  # µm from organoid
    CTRL: 100.0                  # µm from organoid
    monte_carlo_trials: 1       #monte-carlo trials for each distance
