# Corrected default.yaml Configuration (comments outdated, ignore)

# -------- Physical & biological constants --------
alpha: 0.20                      # ECS volume fraction
clearance_rate: 0.1             # s^-1 (k')
detection_bandwidth_Hz: 100      # Detection bandwidth (not sampling rate!)

# -------- Neurotransmitter-specific parameters ----
neurotransmitters:
  DA:
    name: "Dopamine (DA)"
    # Binding (Kd ~150 nM → choose kon=1e5 -> koff=1.5e-2 s^-1)
    k_on_M_s: 1e5
    k_off_s: 0.01
    # Transport
    D_m2_s: 4.9e-10          # aqueous; in tissue your model uses D/λ^2
    lambda: 1.6
    # Device coupling (keep opposite sign vs. SERO to preserve dual-channel separation)
    q_eff_e: -0.35

  SERO:
    name: "Serotonin (5-HT)"
    # Binding (Kd ~30 nM → choose kon=1e5 -> koff=3.0e-3 s^-1)
    k_on_M_s: 1e5
    k_off_s: 0.01
    # Transport (typical small aromatic amine)
    D_m2_s: 5.3e-10
    lambda: 1.6
    # Device coupling (opposite sign to DA)
    q_eff_e: 0.35

  CTRL:
    name: "Control"
    k_on_M_s: 0.0
    k_off_s: 0.0
    D_m2_s: 4.9e-10
    lambda: 1.6
    q_eff_e: 0.0

# -------- Geometry --------
# gate_area_m2: 4e-8              # 200x200 um^2

# -------- Release profile --------
T_release_ms: 10
burst_shape: "rect"             # "rect" | "gamma"
gamma_shape_k: 2.0              # used only if burst_shape == "gamma"
gamma_scale_theta: 5e-3         # s

# -------- Binding layer --------
N_apt: 2e8                      # CORRECTED: Consistent with literature (was 4e8)
binding:
  k_on_M_s: 1e5                 # Changed from k_on_M_inv_s
  k_off_s: 0.1                  # Changed from k_off_s_inv  
  N_sites: 200000
  # N_sites_glu: 4e8              # CORRECTED
  # N_sites_gaba: 4e8             # CORRECTED
  # N_sites_ctrl: 0               # CTRL channel

# -------- OECT device --------
oect:
  gm_S: 0.005                    # 5 mS transconductance
  C_tot_F: 5e-8               # Optimized capacitance (was 4e-7)
  R_ch_Ohm: 500                 # Channel resistance for Johnson noise
  I_dc_A: 1.0e-4                # 100 µA baseline current for proper noise scaling
  V_g_bias_V: -0.2             # -200 mV gate bias

# -------- Noise --------
noise:
  rho_corr: 0.9                 # Also support rho_correlated alias
  rho_correlated: 0.9           # Alias for compatibility
  alpha_H: 1.0e-3               # Reduced 1/f noise (was 3.0e-3)
  K_d_Hz: 0                     # No drift noise (was 1.0e-4)
  N_c: 4.5e11                   # CORRECTED: Literature standard
  effective_correlation: 0.9        # Override for noise calculations
  detection_bandwidth_Hz: 100       # Override detection bandwidth
  rho_between_channels_after_ctrl: 0.5  # residual Corr(DA-CTRL, SERO-CTRL) for symmetric triplet

# -------- Simulation window --------
# monte_carlo_trials: 10000
sim:
  time_window_s: 20
  dt_s: 0.01
  temperature_K: 310.0
  deterministic_mode: false     # Flag: Use means instead of stochastic

# ——— Simulation / figure sweeps ———
# Mode-specific distance grids: dense near transmitter, trimmed tails for performance
lod_distances_um:
  MoSK: [25, 35, 45, 55, 65, 75, 85, 95, 105, 125, 150, 175, 200]
  CSK: [15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 115, 125]
  Hybrid: [15, 20, 25, 30, 35, 40, 45, 55, 65, 75, 85, 95, 105, 115, 125, 150]
# Legacy grids retained for reference
# distances_um: [15, 25, 35, 45, 55, 65, 75, 85, 95, 105, 110, 115, 120, 125, 130, 135, 140, 145, 150]
# distances_um_high_res: [15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 105, 110, 125, 150, 175]
Nm_range: [200,500,1000,1600,2500,4000,6300,10000,16000,25000,40000,63000] # finer resolution

# -------- Detection layer --------
detection:
  modulation: "MoSK"            # MoSK | CSK | hybrid
  decision_window_s: 20         # Use full symbol period (was 8.0)
  # threshold_nA:                 # only used for CSK (2-level) or CTRL threshold tests
    # GLU: 0.75e-9
    # GABA: 0.60e-9
  sequence_length: 1000         # symbols per Monte-Carlo run
  # monte_carlo_trials: 10000
  snr_dB_range: [-10, 20]       # analytic BER curves
  #mu0_glu: 2.442e-05           # Mean charge for GLU class
  #mu1_gaba: -2.620e-05         # Mean charge for GABA class
  show_progress: true          # Show progress bars
  decision_window_policy: full_ts
  decision_window_fraction: 0.9  # integrate the last 90* of Ts
  # optional: min_decision_samples: 32

# -------- End-to-end pipeline --------
pipeline:
  symbol_period_s: 20.0         # Ts from manuscript
  lod_nm_max: 1000000            # Maximum Nm for LoD search (was hardcoded 100k)
  min_symbol_period_s: 5.0      # Minimum symbol period (was hardcoded 20s)
  distance_um: 50               # Changed from 100 to 50 as in code
  Nm_per_symbol: 1e7          # molecules per burst (was 5.0e4)
  sequence_length: 1000         # symbols per Monte-Carlo run
  random_seed: 2025
  modulation: "MoSK"            # Options: "MoSK", "CSK", "Hybrid"
  enable_isi: True              # Master switch for the Inter-Symbol Interference model
  isi_memory: 5                 # Default memory (will be made dynamic in analysis script)
  guard_factor: 0.15             # 20% guard time (Reduced from 0.3)
  lod_nm_min: 50                # New flexible lower bound for LoD search
  csk_target_channel: "DA"     # Defines the molecule used for the pure CSK scheme
  # level_probs: [0.25, 0.25, 0.25, 0.25]  # For energy-fairness calculations
  csk_levels: 4                 # Number of concentration levels for CSK and Hybrid modes
  csk_tail_fraction: 0.6        # Use tail-gating for CSK everywhere
  non_specific_binding_factor: 0.0  # No signal leakage (was 0.05)
  # NEW: Dual-channel CSK configuration
  csk_dual_channel: true          # enable dual-channel CSK
  csk_combiner: "zscore"          # one of: ["zscore","whitened","leakage"]
  csk_leakage_frac: 0.0           # fractional mean leakage on the 'other' channel (0–0.2 typical)
  csk_store_combiner_meta: true   # persist combiner + (σ,ρ) into CSVs
  isi_memory_cap_symbols: 60   # cap the ISI tail
  detector_mode: "zscore"       # Detector statistic: zscore | raw | whitened

  # -------- Advanced Optimization Parameters --------
  # Adaptive calibration tuning (Issue 1 optimization)
  _cal_eps_rel: 0.01              # 1% convergence threshold
  _cal_patience: 2                # Wait 2 iterations before stopping
  _cal_min_seeds: 4               # Minimum seeds before early stopping
  _cal_min_samples_per_class: 50  # Minimum samples per class
  _cal_enable_es_mosk: true       # Enable early stopping for MoSK
  _cal_enable_es_hybrid: true     # Enable early stopping for Hybrid
  # Window guard tuning (Issue 2 optimization)
  _min_decision_points: 4       # Minimum time points for window guard

  # channel_spacing_um: 200       # from paper
  # Channel positions relative to organoid center
  # channel_positions:
    # GLU: {x: -200, y: 0, z: 0}    # μm
    # GABA: {x: 0, y: 0, z: 0}      # μm
    # CTRL: {x: 200, y: 0, z: 0}    # μm
  # Gate dimensions for each channel
  gate_dimensions_um:
    width: 200
    height: 200
  # Aptamer specificity matrix (perfect selectivity assumed)
  # aptamer_specificity:
    # GLU: {GLU: 1.0, GABA: 0.0}    # GLU aptamers only bind GLU
    # GABA: {GLU: 0.0, GABA: 1.0}   # GABA aptamers only bind GABA
    # CTRL: {GLU: 0.0, GABA: 0.0}    # Control must be signal-free for differential subtraction
  # Channel-specific aptamer counts (tri-channel architecture)
  # N_sites_glu: 1.0e9              # Aptamer sites for GLU channel
  # N_sites_gaba: 1.0e9             # Aptamer sites for GABA channel
  # N_sites_ctrl: 0                 # No aptamers on control channel
  enable_molecular_noise: true    # Enable Poisson shot noise
  # channel_distances:
    # GLU: 100.0                   # µm from organoid
    # GABA: 100.0                  # µm from organoid
    # CTRL: 100.0                  # µm from organoid
  # monte_carlo_trials: 10         # monte-carlo trials for analysis
  show_progress: true            # Show progress bars
  verbose: true                # Enable verbose output

# -------- Enhanced Analysis Options --------
analysis:
  # use_effective_data_rate: false     # Use (1-SER) factor in data rate calculations
  # enhanced_noise_model: false       # Enable configurable noise parameters
  # timeout_retry_enabled: true       # Enable timeout retry logic
  # pre_submission_ci_check: true     # Skip job submission when CI already satisfied
  allow_ts_exceed: true  # do not abort the LoD row when Ts gets large
  ts_cap_s: 0            # 0 disables the cap; or set a very high value
  guard_samples_cap: 0  # skip guard sweeps that would require >40M samples per seed (default 4.0e7)
